In [1]:
install.packages("sqldf")
library(sqldf)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite

In [2]:
data <- read.csv("cleaned_main.csv", stringsAsFactors=FALSE)

#Delay By Zone

In [ ]:
sqldf("
SELECT dropoff_zone,
       COUNT(*) AS total_deliveries,
       SUM(delay_flag) AS delayed_deliveries
FROM data
GROUP BY dropoff_zone
ORDER BY delayed_deliveries DESC
")

# Complaint Impact

In [3]:
sqldf("
SELECT has_complaint,
       AVG(delay_flag) AS delay_rate
FROM data
GROUP BY has_complaint
")

  has_complaint delay_rate
1 0             0
2 1             0

# Driver Behaviour (Root Cause)

In [4]:
sqldf("
SELECT driver_id,
       AVG(manual_route_override_count) AS avg_overrides,
       AVG(delay_flag) AS delay_rate
FROM data
GROUP BY driver_id
ORDER BY avg_overrides DESC
")

    driver_id avg_overrides delay_rate
1   D112      4.500000      0
2   D127      2.833333      0
3   D021      2.500000      0
4   D139      2.000000      0
5   D130      2.000000      0
6   D124      2.000000      0
7   D105      2.000000      0
8   D085      2.000000      0
9   D079      2.000000      0
10  D069      2.000000      0
11  D062      2.000000      0
12  D060      2.000000      0
13  D051      2.000000      0
14  D028      1.857143      0
15  D027      1.833333      0
16  D143      1.800000      0
17  D136      1.750000      0
18  D107      1.750000      0
19  D003      1.750000      0
20  D104      1.714286      0
21  D131      1.666667      0
22  D114      1.666667      0
23  D090      1.666667      0
24  D042      1.666667      0
25  D073      1.600000      0
26  D033      1.571429      0
27  D169      1.500000      0
28  D103      1.500000      0
29  D040      1.500000      0
30  D008      1.500000      0
⋮   ⋮         ⋮             ⋮
141 D101      0.4000000     0
142 D092      0.4000000     0
143 D049      0.4000000     0
144 D102      0.3846154     0
145 D164      0.3750000     0
146 D037      0.3750000     0
147 D140      0.3333333     0
148 D093      0.3333333     0
149 D063      0.3333333     0
150 D045      0.3333333     0
151 D034      0.3333333     0
152 D023      0.3333333     0
153 D015      0.3333333     0
154 D155      0.2857143     0
155 D018      0.2857143     0
156 D167      0.2500000     0
157 D128      0.2500000     0
158 D064      0.2500000     0
159 D061      0.2500000     0
160 D058      0.2500000     0
161 D014      0.2500000     0
162 D091      0.1666667     0
163 D071      0.1428571     0
164 D161      0.0000000     0
165 D109      0.0000000     0
166 D081      0.0000000     0
167 D029      0.0000000     0
168 D025      0.0000000     0
169 D012      0.0000000     0
170 D007      0.0000000     0

# Cost Analysis

In [5]:
sqldf("
SELECT dropoff_zone,
       AVG(fuel_or_charge_cost) AS avg_cost
FROM data
GROUP BY dropoff_zone
ORDER BY avg_cost DESC
")

  dropoff_zone avg_cost
1 North        13.33759
2 Riverside    13.20709
3 West         13.15644
4 East         12.91644
5 Central      12.66041
6 Ctr          12.65918
7 South        12.35885
8 Airport      12.11732

# Combined Failure Analysis

In [6]:
sqldf("
SELECT dropoff_zone,
       COUNT(*) AS total,
       SUM(delay_flag) AS delays,
       SUM(has_complaint) AS complaints
FROM data
GROUP BY dropoff_zone
")

  dropoff_zone total delays complaints
1 Airport      123   0      33
2 Central       98   0      21
3 Ctr           49   0       7
4 East         118   0      24
5 North        145   0      32
6 Riverside    141   0      26
7 South        130   0      34
8 West         146   0      32